[tools]
luau-lsp = { source = "JohnnyMorganz/luau-lsp", version = "1.x" }
lune = { source = "lune-org/lune", version = "0.8.0" }
rojo = { source = "rojo-rbx/rojo", version = "7.3.0" }
selene = { source = "Kampfkarren/selene", version = "0.26.1" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.20.0" }
